name: 'Prepare Build'
description: 'Help preparing build'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: >
        sudo apt-get install -y cmake build-essential pkg-config
        apt-utils g++-9 gcc-10 g++-10 git odb python3 python3-pip
      shell: bash
    - run: sudo pip3 install conan
      shell: bash
    - name: Export vendored conan packages
      run: >
        (cd vendor/libodb && conan export .) &&
        (cd vendor/libodb-boost && conan export .) &&
        (cd vendor/libodb-pgsql && conan export .) &&
        (cd vendor/libodb-sqlite && conan export .) &&
        (cd vendor/libscrypt && conan export .)
      shell: bash