ARG LEOSAC_BASE_DOCKER=leosac_base
FROM ${LEOSAC_BASE_DOCKER}

RUN apt-get update
RUN sudo apt-get install -y gcc-10-aarch64-linux-gnu g++-10-aarch64-linux-gnu

RUN mkdir build
WORKDIR /leosac_repository/build
RUN conan install --build missing --profile:build ../conan/profile --profile:host ../conan/profilearm64 ..
RUN conan build ..
