name: Conan
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ develop ]

jobs:
  # Sadly we make an independent run for unittest.
  unittest_x64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/install-build-deps
      - uses: ./.github/actions/conan-install-build-package-for-profile
        with:
          host-profile: ${{ github.workspace }}/conan/profile
          build-dir: build_x64
      - name: Run ctest
        run: ctest .

  build_x64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/install-build-deps
      - uses: ./.github/actions/conan-install-build-package-for-profile
        with:
          host-profile: ${{ github.workspace }}/conan/profile
          build-dir: build_x64
      - uses: actions/upload-artifact@v3
        with:
          name: leosac-package-x64
          path: build_x64/package/
          retention-days: 2

  build_arm64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/install-build-deps
      - name: Install additional compiler
        run: >
          sudo apt-get install -y gcc-10-aarch64-linux-gnu g++-10-aarch64-linux-gnu
      - uses: ./.github/actions/conan-install-build-package-for-profile
        with:
          host-profile: ${{ github.workspace }}/conan/profilearm64
          build-dir: build_arm64
      - uses: actions/upload-artifact@v3
        with:
          name: leosac-package-arm64
          path: build_arm64/package/
          retention-days: 2

  build_arm-linux-gnueabi:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/install-build-deps
      - name: Install additional compiler
        run: >
          sudo apt-get install -y g++-10-arm-linux-gnueabi gcc-10-arm-linux-gnueabi
      - uses: ./.github/actions/conan-install-build-package-for-profile
        with:
          host-profile: ${{ github.workspace }}/conan/profilearm32
          build-dir: build_arm32
      - uses: actions/upload-artifact@v3
        with:
          name: leosac-package-arm32
          path: build_arm32/package/
          retention-days: 2
